string class_name               # filter for class name and select object with highest probability (If empty, select highest from all classes)
string base_frame               # point is given relative to this reference frame
string camera_type              # used camera for depth image ("roboception" or "realsense")
---
geometry_msgs/Point point       # xyz of point in [m]
float64 probability             # probability of detected object
string class_name               # class_name of detected object
